db:
  image: library/postgres:9.6.5
  restart: always
  environment:
      POSTGRES_PASSWORD: example
  volumes:
    - ./DATA/pg/data:/var/lib/postgresql/data

cron:
  build: docker-pg_dump
  restart: always
  environment:
    PGUSER: postgres
    PGPASSWORD: example
    CRON_SCHEDULE: 0 1 * * *
  links:
    - db
  volumes:
    - ./DATA/dump:/dump
  command: dump-cron

adminer:
  image: adminer
  restart: always
  links:
    - db
  ports:
    - 8080:8080
